{
    'name': 'Sky Account Company',
    'version': '13.0.0.1',
    'category': 'Account',
    'description': """
    This module is for account company""",
    'author': 'Skyscend Business Solutions',
    'website': 'http://www.skyscendbs.com',
    'depends': ['account', 'base_accounting_kit'],
    'data': [
        'security/base_groups.xml',
        'views/account_asset_views.xml',
        'views/account_followup.xml',
        'views/account_move_views.xml',
        'views/account_payment_views.xml',
        'views/product_template_views.xml',
        'views/account_general_ledger_views.xml',
        'views/account_partner_ledger_views.xml',
        'views/account_payment_terms_views.xml',
        'views/account_fiscal_position_views.xml',
        'views/account_analytic_views.xml',
        'views/account_analytic_tag_views.xml',
        'views/account_analytic_groups_views.xml',
        'views/account_analytic_items_views.xml',
        'views/account_taxes_views.xml',
        'views/account_journals_views.xml',
        'views/account_bank_accounts_views.xml',
        'views/account_payment_acquirer_views.xml',
        'views/account_sales_team_views.xml',
        'views/account_coa_views.xml',
        'views/sale_views.xml',
        'views/account_journal_group_views.xml',
        'views/account_customers_vendors_view.xml',
        'wizard/account_bank_book_wizard_view.xml',
        'wizard/account_cash_book_wizard_view.xml',
        'wizard/account_day_book_wizard_view.xml',
        'wizard/account_lock_date.xml',
        'report/account_asset_report_views.xml',
        'report/account_partner_ledger_report_template.xml',
        'report/account_tax_report_template.xml',
        'report/account_journal_audit_template.xml',
        'report/account_invoice_analysis_report.xml',
        'report/account_sales_analysis_report_views.xml',
        'wizard/financial_report.xml',
        'wizard/account_cash_flow_statement_wizard_views.xml',
        'wizard/account_trail_balance_wizard_views.xml',
        'wizard/account_tax_report_wizard_views.xml',
        'wizard/account_journal_audit_wizard_views.xml',
        'views/recurring_payments_view.xml',

    ],
    'installable': True,
    'auto_install': False
}
