{
    'name': 'Hotel Mangement',
    'description': 'A module is use for managea hospital system',
    'version': '1.0',
    'author': 'Skyscend Business Solution Pvt.Ltd.',
    'website': 'www.skyscendbs.com',
    'depends': ['base', 'mail'],
    'data': [

        'security/hotel_security.xml',
        'security/ir.models.access.csv',
        'views/main_menu_view.xml',
        'data/customer_sequence.xml',
        'data/customer_number_check_parameters.xml',
        'data/customer_data.xml',
        'data/customer.room.csv',
        'data/customer_print_wizard_email_template.xml',
        'data/customer_server_action.xml',
        'data/amenities_cron.xml',
        'data/company_property.xml',
        'data/customer_email_template.xml',
        'wizard/add_charges_wiz_view.xml',
        'wizard/print_customer_report_wiz.xml',
        'wizard/show_m2o_record_view.xml',
        'wizard/update_age_wiz_view.xml',
        'wizard/customer_xls_report.xml',
        'wizard/display_rooms_m2o_record.xml',
        'wizard/email_template_print_wiz.xml',
        'wizard/Exe_nine_open_wiz.xml',
        'wizard/new_print_customer_report_wiz.xml',
        'wizard/call_second_wizard.xml',
        'wizard/call_first_wizard.xml',
        'views/customer_charges_view.xml',
        'views/customer_view.xml',
        'views/customer_room_view.xml',
        'views/customer_amenities_view.xml',
        'views/customer_services_view.xml',
        'views/templates.xml',
        'views/res_config_setting.xml',
        'demo/customer_demo.xml',
        'demo/room_demo.xml',
        'demo/customer.customer.csv',
        'report/customer_analysis_view.xml',
        'report/report_customer_template.xml',
        'report/hotel_report.xml',
        'report/new_customer_template.xml',
        'report/new_report.xml',

    ],
    'auto_install': False,
    'application': True
}
