from . import update_age_wiz
from . import add_Charges
from . import show_m2o_record
from . import print_customer_report_wiz
from . import customer_xls_report
from . import display_rooms_m2o_record
from . import new_print_customer_report_wiz
from . import email_template_print_wiz
from . import Exe_nine_open_wiz
from . import call_second_wizard
from . import call_first_wizard
